services:
  product-app:
    build: .
    container_name: product_app
    ports:
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_REDIS_HOST=redis-cache
      - SPRING_REDIS_PORT=6397
    depends_on:
      - postgres-db
      - redis-cache
    networks:
      - product_network

  postgres-db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - product_network

  redis-cache:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    networks:
      - product_network

networks:
  product_network:
    driver: bridge
volumes:
  postgres_data:
